"""empty message

Revision ID: 4e6146e6959c
Revises: eb77c96cc00f
Create Date: 2021-05-29 15:15:42.339186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e6146e6959c'
down_revision = 'eb77c96cc00f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('image_path', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'image_path')
    # ### end Alembic commands ###
