"""empty message

Revision ID: 56eab3fde1fc
Revises: 7b82e0332abe
Create Date: 2021-05-30 15:58:14.579867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56eab3fde1fc'
down_revision = '7b82e0332abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testimonial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('appraisal', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testimonial_appraisal'), 'testimonial', ['appraisal'], unique=False)
    op.create_index(op.f('ix_testimonial_created_at'), 'testimonial', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testimonial_created_at'), table_name='testimonial')
    op.drop_index(op.f('ix_testimonial_appraisal'), table_name='testimonial')
    op.drop_table('testimonial')
    # ### end Alembic commands ###
